#!/bin/bash
#SBATCH -J maketest           # job name
#SBATCH -o maketest%j       # output and error file name (%j expands to jobID)
#SBATCH -N 2              # total number of nodes
#SBATCH -n 4              # total number of cores
#SBATCH -p gtx     # queue (partition) -- normal, development, etc.
#SBATCH -t 00:01:30        # run time (hh:mm:ss) - 20 seconds
#SBATCH -A EE-382C-EE-361C-Mult
#SBATCH --mail-user=john.koelling@utexas.edu # replace by your email

. generic_test.sh brick_sort
